/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'joel' at '6/2/16 10:36 PM' with Gradle 2.13
 *
 * @author joel, @date 6/2/16 10:36 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
